// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0--rc1
// source: lease_rpc.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WriteDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *WriteDataRequest) Reset() {
	*x = WriteDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lease_rpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteDataRequest) ProtoMessage() {}

func (x *WriteDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lease_rpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteDataRequest.ProtoReflect.Descriptor instead.
func (*WriteDataRequest) Descriptor() ([]byte, []int) {
	return file_lease_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *WriteDataRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WriteDataRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type WriteDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State int32 `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *WriteDataResponse) Reset() {
	*x = WriteDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lease_rpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteDataResponse) ProtoMessage() {}

func (x *WriteDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lease_rpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteDataResponse.ProtoReflect.Descriptor instead.
func (*WriteDataResponse) Descriptor() ([]byte, []int) {
	return file_lease_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *WriteDataResponse) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

type RequestDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataName string `protobuf:"bytes,1,opt,name=data_name,json=dataName,proto3" json:"data_name,omitempty"`
}

func (x *RequestDataRequest) Reset() {
	*x = RequestDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lease_rpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDataRequest) ProtoMessage() {}

func (x *RequestDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lease_rpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDataRequest.ProtoReflect.Descriptor instead.
func (*RequestDataRequest) Descriptor() ([]byte, []int) {
	return file_lease_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *RequestDataRequest) GetDataName() string {
	if x != nil {
		return x.DataName
	}
	return ""
}

type RequestDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data  string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Lease int64  `protobuf:"varint,2,opt,name=lease,proto3" json:"lease,omitempty"`
}

func (x *RequestDataResponse) Reset() {
	*x = RequestDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lease_rpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDataResponse) ProtoMessage() {}

func (x *RequestDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lease_rpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDataResponse.ProtoReflect.Descriptor instead.
func (*RequestDataResponse) Descriptor() ([]byte, []int) {
	return file_lease_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *RequestDataResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *RequestDataResponse) GetLease() int64 {
	if x != nil {
		return x.Lease
	}
	return 0
}

type OutdateDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataName string `protobuf:"bytes,1,opt,name=data_name,json=dataName,proto3" json:"data_name,omitempty"`
}

func (x *OutdateDataRequest) Reset() {
	*x = OutdateDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lease_rpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutdateDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutdateDataRequest) ProtoMessage() {}

func (x *OutdateDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lease_rpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutdateDataRequest.ProtoReflect.Descriptor instead.
func (*OutdateDataRequest) Descriptor() ([]byte, []int) {
	return file_lease_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *OutdateDataRequest) GetDataName() string {
	if x != nil {
		return x.DataName
	}
	return ""
}

type OutdateDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *OutdateDataResponse) Reset() {
	*x = OutdateDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lease_rpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutdateDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutdateDataResponse) ProtoMessage() {}

func (x *OutdateDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lease_rpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutdateDataResponse.ProtoReflect.Descriptor instead.
func (*OutdateDataResponse) Descriptor() ([]byte, []int) {
	return file_lease_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *OutdateDataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ReadDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataName string `protobuf:"bytes,1,opt,name=data_name,json=dataName,proto3" json:"data_name,omitempty"`
}

func (x *ReadDataRequest) Reset() {
	*x = ReadDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lease_rpc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDataRequest) ProtoMessage() {}

func (x *ReadDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lease_rpc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDataRequest.ProtoReflect.Descriptor instead.
func (*ReadDataRequest) Descriptor() ([]byte, []int) {
	return file_lease_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *ReadDataRequest) GetDataName() string {
	if x != nil {
		return x.DataName
	}
	return ""
}

type ReadDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ReadDataResponse) Reset() {
	*x = ReadDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lease_rpc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDataResponse) ProtoMessage() {}

func (x *ReadDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lease_rpc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDataResponse.ProtoReflect.Descriptor instead.
func (*ReadDataResponse) Descriptor() ([]byte, []int) {
	return file_lease_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *ReadDataResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_lease_rpc_proto protoreflect.FileDescriptor

var file_lease_rpc_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x3a, 0x0a, 0x10, 0x57, 0x72, 0x69, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x29, 0x0a,
	0x11, 0x57, 0x72, 0x69, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x31, 0x0a, 0x12, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b,
	0x0a, 0x09, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x3f, 0x0a, 0x13, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x22, 0x31, 0x0a, 0x12,
	0x4f, 0x75, 0x74, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0x2f, 0x0a, 0x13, 0x4f, 0x75, 0x74, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x22, 0x2e, 0x0a, 0x0f, 0x52, 0x65, 0x61, 0x64, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x26, 0x0a, 0x10, 0x52, 0x65, 0x61, 0x64, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x76, 0x0a, 0x09, 0x43, 0x61, 0x63, 0x68,
	0x65, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x38, 0x0a, 0x0b, 0x4f, 0x75, 0x74, 0x64, 0x61, 0x74, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x13, 0x2e, 0x4f, 0x75, 0x74, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x4f, 0x75, 0x74, 0x64,
	0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2f, 0x0a, 0x08, 0x52, 0x65, 0x61, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x10, 0x2e, 0x52, 0x65,
	0x61, 0x64, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e,
	0x52, 0x65, 0x61, 0x64, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x32, 0x7a, 0x0a, 0x0a, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x38,
	0x0a, 0x0b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x13, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x14, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x09, 0x57, 0x72, 0x69, 0x74,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x11, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x06, 0x5a, 0x04,
	0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lease_rpc_proto_rawDescOnce sync.Once
	file_lease_rpc_proto_rawDescData = file_lease_rpc_proto_rawDesc
)

func file_lease_rpc_proto_rawDescGZIP() []byte {
	file_lease_rpc_proto_rawDescOnce.Do(func() {
		file_lease_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_lease_rpc_proto_rawDescData)
	})
	return file_lease_rpc_proto_rawDescData
}

var file_lease_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_lease_rpc_proto_goTypes = []any{
	(*WriteDataRequest)(nil),    // 0: WriteDataRequest
	(*WriteDataResponse)(nil),   // 1: WriteDataResponse
	(*RequestDataRequest)(nil),  // 2: RequestDataRequest
	(*RequestDataResponse)(nil), // 3: RequestDataResponse
	(*OutdateDataRequest)(nil),  // 4: OutdateDataRequest
	(*OutdateDataResponse)(nil), // 5: OutdateDataResponse
	(*ReadDataRequest)(nil),     // 6: ReadDataRequest
	(*ReadDataResponse)(nil),    // 7: ReadDataResponse
}
var file_lease_rpc_proto_depIdxs = []int32{
	4, // 0: CacheNode.OutdateData:input_type -> OutdateDataRequest
	6, // 1: CacheNode.ReadData:input_type -> ReadDataRequest
	2, // 2: CenterNode.RequestData:input_type -> RequestDataRequest
	0, // 3: CenterNode.WriteData:input_type -> WriteDataRequest
	5, // 4: CacheNode.OutdateData:output_type -> OutdateDataResponse
	7, // 5: CacheNode.ReadData:output_type -> ReadDataResponse
	3, // 6: CenterNode.RequestData:output_type -> RequestDataResponse
	1, // 7: CenterNode.WriteData:output_type -> WriteDataResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lease_rpc_proto_init() }
func file_lease_rpc_proto_init() {
	if File_lease_rpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lease_rpc_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*WriteDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lease_rpc_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*WriteDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lease_rpc_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*RequestDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lease_rpc_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*RequestDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lease_rpc_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*OutdateDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lease_rpc_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*OutdateDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lease_rpc_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*ReadDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lease_rpc_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*ReadDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lease_rpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_lease_rpc_proto_goTypes,
		DependencyIndexes: file_lease_rpc_proto_depIdxs,
		MessageInfos:      file_lease_rpc_proto_msgTypes,
	}.Build()
	File_lease_rpc_proto = out.File
	file_lease_rpc_proto_rawDesc = nil
	file_lease_rpc_proto_goTypes = nil
	file_lease_rpc_proto_depIdxs = nil
}
