// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0--rc2
// source: lease_rpc.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OutdateDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataName string `protobuf:"bytes,1,opt,name=data_name,json=dataName,proto3" json:"data_name,omitempty"`
}

func (x *OutdateDataRequest) Reset() {
	*x = OutdateDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lease_rpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutdateDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutdateDataRequest) ProtoMessage() {}

func (x *OutdateDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lease_rpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutdateDataRequest.ProtoReflect.Descriptor instead.
func (*OutdateDataRequest) Descriptor() ([]byte, []int) {
	return file_lease_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *OutdateDataRequest) GetDataName() string {
	if x != nil {
		return x.DataName
	}
	return ""
}

type OutdateDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *OutdateDataResponse) Reset() {
	*x = OutdateDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lease_rpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutdateDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutdateDataResponse) ProtoMessage() {}

func (x *OutdateDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lease_rpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutdateDataResponse.ProtoReflect.Descriptor instead.
func (*OutdateDataResponse) Descriptor() ([]byte, []int) {
	return file_lease_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *OutdateDataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RequestDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataName string `protobuf:"bytes,1,opt,name=data_name,json=dataName,proto3" json:"data_name,omitempty"`
}

func (x *RequestDataRequest) Reset() {
	*x = RequestDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lease_rpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDataRequest) ProtoMessage() {}

func (x *RequestDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lease_rpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDataRequest.ProtoReflect.Descriptor instead.
func (*RequestDataRequest) Descriptor() ([]byte, []int) {
	return file_lease_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *RequestDataRequest) GetDataName() string {
	if x != nil {
		return x.DataName
	}
	return ""
}

type RequestDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data  string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Lease int64  `protobuf:"varint,2,opt,name=lease,proto3" json:"lease,omitempty"`
}

func (x *RequestDataResponse) Reset() {
	*x = RequestDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lease_rpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDataResponse) ProtoMessage() {}

func (x *RequestDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lease_rpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDataResponse.ProtoReflect.Descriptor instead.
func (*RequestDataResponse) Descriptor() ([]byte, []int) {
	return file_lease_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *RequestDataResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *RequestDataResponse) GetLease() int64 {
	if x != nil {
		return x.Lease
	}
	return 0
}

var File_lease_rpc_proto protoreflect.FileDescriptor

var file_lease_rpc_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x31, 0x0a, 0x12, 0x4f, 0x75, 0x74, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0x2f, 0x0a, 0x13, 0x4f, 0x75, 0x74, 0x64, 0x61, 0x74, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x31, 0x0a, 0x12, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x64,
	0x61, 0x74, 0x61, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x64, 0x61, 0x74, 0x61, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x3f, 0x0a, 0x13, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x32, 0x45, 0x0a, 0x09, 0x43, 0x61, 0x63,
	0x68, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x38, 0x0a, 0x0b, 0x4f, 0x75, 0x74, 0x64, 0x61, 0x74,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x13, 0x2e, 0x4f, 0x75, 0x74, 0x64, 0x61, 0x74, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x4f, 0x75, 0x74,
	0x64, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x32, 0x46, 0x0a, 0x0a, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x38,
	0x0a, 0x0b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x13, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x14, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lease_rpc_proto_rawDescOnce sync.Once
	file_lease_rpc_proto_rawDescData = file_lease_rpc_proto_rawDesc
)

func file_lease_rpc_proto_rawDescGZIP() []byte {
	file_lease_rpc_proto_rawDescOnce.Do(func() {
		file_lease_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_lease_rpc_proto_rawDescData)
	})
	return file_lease_rpc_proto_rawDescData
}

var file_lease_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_lease_rpc_proto_goTypes = []any{
	(*OutdateDataRequest)(nil),  // 0: OutdateDataRequest
	(*OutdateDataResponse)(nil), // 1: OutdateDataResponse
	(*RequestDataRequest)(nil),  // 2: RequestDataRequest
	(*RequestDataResponse)(nil), // 3: RequestDataResponse
}
var file_lease_rpc_proto_depIdxs = []int32{
	0, // 0: CacheNode.OutdateData:input_type -> OutdateDataRequest
	2, // 1: CenterNode.RequestData:input_type -> RequestDataRequest
	1, // 2: CacheNode.OutdateData:output_type -> OutdateDataResponse
	3, // 3: CenterNode.RequestData:output_type -> RequestDataResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lease_rpc_proto_init() }
func file_lease_rpc_proto_init() {
	if File_lease_rpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lease_rpc_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*OutdateDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lease_rpc_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*OutdateDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lease_rpc_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*RequestDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lease_rpc_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*RequestDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lease_rpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_lease_rpc_proto_goTypes,
		DependencyIndexes: file_lease_rpc_proto_depIdxs,
		MessageInfos:      file_lease_rpc_proto_msgTypes,
	}.Build()
	File_lease_rpc_proto = out.File
	file_lease_rpc_proto_rawDesc = nil
	file_lease_rpc_proto_goTypes = nil
	file_lease_rpc_proto_depIdxs = nil
}
